import type { AuditRequest, AuditResult } from "./types";

const auditRequestContractFixture = {
  url: "https://example.com/",
  include_protocols: true,
  include_account_auth: false,
  include_ecommerce: false,
} satisfies AuditRequest;

const auditResultContractFixture = {
  url: "https://example.com/",
  scope: {
    include_protocols: true,
    include_account_auth: false,
    include_ecommerce: false,
    label: "Protocols included",
    included_optional_surfaces: ["protocols"],
    excluded_optional_surfaces: ["account_auth", "ecommerce"],
    preset_applied: null,
    overrides_applied: {},
    included_families: [],
    excluded_families: [],
    machine_surfaces_scope: "common-contextual",
  },
  overall_score: 75,
  pillar_scores: {
    off_site: 20,
    scrapability: 30,
    seo: 25,
  },
  pillar_max: {
    off_site: 25,
    scrapability: 40,
    seo: 35,
  },
  agent_readiness: {
    score: 80,
    earned: 8,
    max: 10,
    label: "Strong",
    categories: [
      {
        name: "Discovery",
        earned: 4,
        max: 5,
        score: 80,
        passed: ["robots.txt"],
        missing: ["agent catalog"],
        excluded: ["account-authenticated actions"],
      },
    ],
    passed: ["robots.txt"],
    missing: ["agent catalog"],
    not_checked: ["account-authenticated actions"],
    benchmark: {
      score: 80,
      earned: 8,
      max: 10,
      benchmark_count: 1,
      median_score: 70,
      percentile: 75,
      position_label: "Above median",
      nearest: [
        {
          name: "Example benchmark",
          category: "reference",
          group: "sample",
          size: "medium",
          url: "https://benchmark.example/",
          overall_score: 72,
          free_evidence_score: 68,
          checked_score: 34,
          checked_max: 50,
          agent_readiness_score: 70,
          agent_readiness_earned: 7,
          agent_readiness_max: 10,
          pillar_scores: {
            off_site: 18,
            scrapability: 28,
            seo: 26,
          },
        },
      ],
      entries: [
        {
          name: "Example benchmark",
          category: "reference",
          group: "sample",
          size: "medium",
          url: "https://benchmark.example/",
          overall_score: 72,
          free_evidence_score: 68,
          checked_score: 34,
          checked_max: 50,
          agent_readiness_score: 70,
          agent_readiness_earned: 7,
          agent_readiness_max: 10,
          pillar_scores: {
            off_site: 18,
            scrapability: 28,
            seo: 26,
          },
        },
      ],
      basis: "Public sample benchmark",
      snapshot_date: "2026-07-16",
      caveat: "Benchmark context is not a visibility guarantee.",
    },
    caveat: "Agent-readiness evidence does not prove agent adoption.",
  },
  benchmark: {
    score: 68,
    checked_score: 34,
    checked_max: 50,
    benchmark_count: 1,
    median_score: 65,
    percentile: 60,
    position_label: "Above median",
    nearest: [
      {
        name: "Example benchmark",
        category: "reference",
        group: "sample",
        size: "medium",
        url: "https://benchmark.example/",
        overall_score: 72,
        free_evidence_score: 68,
        checked_score: 34,
        checked_max: 50,
        agent_readiness_score: 70,
        agent_readiness_earned: 7,
        agent_readiness_max: 10,
        pillar_scores: {
          off_site: 18,
          scrapability: 28,
          seo: 26,
        },
      },
    ],
    entries: [
      {
        name: "Example benchmark",
        category: "reference",
        group: "sample",
        size: "medium",
        url: "https://benchmark.example/",
        overall_score: 72,
        free_evidence_score: 68,
        checked_score: 34,
        checked_max: 50,
        agent_readiness_score: 70,
        agent_readiness_earned: 7,
        agent_readiness_max: 10,
        pillar_scores: {
          off_site: 18,
          scrapability: 28,
          seo: 26,
        },
      },
    ],
    basis: "Included free checks",
    snapshot_date: "2026-07-16",
    caveat: "Benchmark context is not a visibility guarantee.",
  },
  checks: [
    {
      pillar: "scrapability",
      check_name: "robots_txt",
      label: "robots.txt",
      state: "pass",
      evidence_level: "verified",
      available_in: "essentials",
      score: 5,
      max_score: 5,
      finding: "robots.txt is publicly available.",
      fix: "No change needed.",
      effort: "low",
    },
  ],
} satisfies AuditResult;
